### PR TITLE
CI: Fix warnings & deprecation messages in the workflows

### PR DESCRIPTION
**Pull request by ljubon**
### What type of PR is this?

CI: Resolve deprecation & warning messages in workflows 
Enable DependaBot for GitHub actions

### What this PR does / why we need it:

Node16 has been out of support since [September 2023](https://github.com/nodejs/Release/#end-of-life-releases). - more info in the [post](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/) 
 
### Which issue(s) this PR fixes:

https://github.com/G-Research/gr-oss/issues/710

### CODE REVIEW

**Comment by pavlovic-ivan** [comment]
Hi @EnricoMi. I just wanted to sync up with you on this PR. Can you take a look, and review? Thx

**Comment by EnricoMi** [comment]
@pavlovic-ivan @ljubon how do you plan to move this upstream?

**Comment by pavlovic-ivan** [comment]
Either as a PR from our fork, or as a PR from GR fork. Question here is do you agree with the changes.

**Review by EnricoMi — APPROVED** [review]

**Comment by EnricoMi** [comment]
@pavlovic-ivan can you please move this upstream?

Once this is in upstream Horovod, how do you plan to handle this fork's master diverging from upstream master? How do we keep them in sync?

**Comment by pavlovic-ivan** [comment]
I'll worry about syncing, and resolving that. How urgent is this request?

**Comment by pavlovic-ivan** [comment]
Resolved

**Pull request merged**
